name: learn-github-actions
on:
  push:
    branches:
      - main
jobs:
  deploy-docs:
    steps:
      - uses: actions/checkout@v3
      - uses: sergioramos/yarn-actions/install@v6
        with:
          frozen-lockfile: true
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: yarn -v
      - run: yarn
      - run: yarn docs:build
